### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by ghost** [BlissRoms/platform_bionic#1]
In file included from bionic/libc/include/fcntl.h:95:
bionic/libc/include/bits/fortify/fcntl.h:63:26: error: use of undeclared identifier 'O_TMPFILE'
        __clang_error_if(__open_modes_useful(flags), "'open' " __open_too_few_args_error) {
                         ^
bionic/libc/include/bits/fortify/fcntl.h:46:71: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                      ^
bionic/libc/include/bits/fortify/fcntl.h:63:26: error: use of undeclared identifier 'O_TMPFILE'
bionic/libc/include/bits/fortify/fcntl.h:46:85: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                                    ^
bionic/libc/include/bits/fortify/fcntl.h:70:29: error: use of undeclared identifier 'O_TMPFILE'
        __clang_warning_if(!__open_modes_useful(flags) && modes,
                            ^
bionic/libc/include/bits/fortify/fcntl.h:46:71: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                      ^
bionic/libc/include/bits/fortify/fcntl.h:70:29: error: use of undeclared identifier 'O_TMPFILE'
bionic/libc/include/bits/fortify/fcntl.h:46:85: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                                    ^
bionic/libc/include/bits/fortify/fcntl.h:83:26: error: use of undeclared identifier 'O_TMPFILE'
        __clang_error_if(__open_modes_useful(flags), "'openat' " __open_too_few_args_error) {
                         ^
bionic/libc/include/bits/fortify/fcntl.h:46:71: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                      ^
bionic/libc/include/bits/fortify/fcntl.h:83:26: error: use of undeclared identifier 'O_TMPFILE'
bionic/libc/include/bits/fortify/fcntl.h:46:85: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                                    ^
bionic/libc/include/bits/fortify/fcntl.h:90:29: error: use of undeclared identifier 'O_TMPFILE'
        __clang_warning_if(!__open_modes_useful(flags) && modes,
                            ^
bionic/libc/include/bits/fortify/fcntl.h:46:71: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                      ^
bionic/libc/include/bits/fortify/fcntl.h:90:29: error: use of undeclared identifier 'O_TMPFILE'
bionic/libc/include/bits/fortify/fcntl.h:46:85: note: expanded from macro '__open_modes_useful'
#define __open_modes_useful(flags) (((flags) & O_CREAT) || ((flags) & O_TMPFILE) == O_TMPFILE)
                                                                                    ^

**Comment by Sikoka1989** [comment]
how did you fix the error?
